### ISSUE TITLE
Make Netdata scraping more pemanent

### ISSUE THREAD

**Issue by rafaribe** [rafaribe/home-ops#1912]
/etc/netdata/netdata.conf gets overwritten every time that truenas boots, also exporting.conf

We need to make a script to copy this after reboot.

exporting.conf:
```toml
[exporting:global]
    enabled = yes
    # send configured labels = yes
    # send automatic labels = no
    # update every = 10

[prometheus:exporter]
     data source = average
     send names instead of ids = yes
     send configured labels = yes
    # send automatic labels = no
     send charts matching = *
    # send hosts matching = localhost *
     prefix = netdata
```

```toml
[global]
        run as user = netdata
        web files owner = root
        web files group = root
        # Netdata is not designed to be exposed to potentially hostile
        # networks. See https://github.com/netdata/netdata/issues/164
        bind socket to IP = 0.0.0.0:6999
        update_every = 2
```
